global:
  scrape_interval: 15s # Default scrape interval
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    # Scrape Prometheus itself
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mcp_services'
    # Use static configs for Docker Compose service names
    # Assumes each MCP service will expose metrics on port 9091
    static_configs:
      - targets:
          - '00_master_mcp:8000'
          - '01_linux_cli_mcp:5001'
          - '02_windows_mcp:9091'
          - '03_azure_mcp:9091'
          - '04_google_cloud_mcp:9091'
          - '05_vmware_mcp:9091'
          - '06_web_search_mcp:9091'
          - '07_web_browsing_mcp:9091'
          - '08_k8s_mcp:9091'
          - '09_n8n_mcp:9091'
          - '10_macos_mcp:9091'
          - '11_freqtrade_mcp:9091'
          - '12_cmdb_mcp:5012'
          - '13_secrets_mcp:8013'
    relabel_configs:
      - source_labels: [__address__]
        regex: '(00_master_mcp:8000|01_linux_cli_mcp:5001|12_cmdb_mcp:5012|13_secrets_mcp:8013)'
        target_label: __metrics_path__
        replacement: /metrics
    # Alternatively, use Docker service discovery if preferred:
    # docker_sd_configs:
    #   - host: unix:///var/run/docker.sock
    # relabel_configs:
    #   # Only scrape containers on the mcp-network
    #   - source_labels: [__meta_docker_network_name]
    #     regex: mcp-network
    #     action: keep
    #   # Only scrape containers exposing the metrics port
    #   - source_labels: [__meta_docker_container_port_private]
    #     regex: "9091"
    #     action: keep
    #   # Use container name as instance label
    #   - source_labels: [__meta_docker_container_name]
    #     regex: "/(.*)"
    #     target_label: instance
    #   # Use service name as job label
    #   - source_labels: [__meta_docker_compose_service]
    #     target_label: job 